name = "trj-result"
version = "0.1.0"
license = "LICENSE"
author = "poponta"
maintainer = "34686350+poponta1218@users.noreply.github.com"
copyright = "Copyright 2025, poponta"
[build]
  auto-executables = true
  auto-tests = true
  auto-examples = true
  module-naming = false
[install]
  library = false
  test = false
[fortran]
  implicit-typing = false
  implicit-external = false
  source-form = "free"
[dependencies.fortchem]
  git = "https://github.com/poponta1218/fortchem"
  branch = "feature/#5-generalize-get_struc"
